# =============================================================================
# STAGING ENVIRONMENT CONFIGURATION
# =============================================================================
# Purpose: Pre-production testing and validation
# Pattern: Agents live in data database, then get added to Snowflake Intelligence
# =============================================================================

environment: staging

# Snowflake connection
snowflake:
  connection_name: snowflake_agents

# Agent deployment location (agents live WITH your data)
agent_deployment:
  database: SKI_RESORT_DB
  schema: AGENTS

  # Add to Snowflake Intelligence for UI visibility
  add_to_snowflake_intelligence: true

# Data sources
data_sources:
  database: SKI_RESORT_DB
  semantic_schema: SEMANTIC

# Compute
warehouse: COMPUTE_WH

# Orchestration model
# Options: auto, claude-haiku-4-5, claude-sonnet-4-5, claude-sonnet-4,
#          claude-sonnet-3-7, claude-sonnet-3-5, gpt-5, gpt-4-1
model:
  orchestration: claude-sonnet-4-5

# Staging-specific settings
settings:
  log_level: INFO
  enable_testing: true
  version_suffix: "_STAGING"
  strict_validation: true

# Promotion criteria to prod
promotion_criteria:
  min_test_coverage: 80
  required_reviews: 1
  min_staging_days: 1
