"""
Email Formatter UDF Handler
Converts agent markdown responses to beautifully styled HTML emails.

Deployed via snowflake.yml as: SKI_RESORT_DB.MODELS.FORMAT_ALERT_EMAIL

Uses premailer to inline CSS for email client compatibility.
"""

import markdown
from premailer import Premailer
from datetime import datetime


def format_email(question: str, response: str) -> str:
    """
    Format agent response as a styled HTML email.

    Args:
        question: The original question asked
        response: Agent's markdown response

    Returns:
        Fully styled HTML email with inlined CSS
    """
    # Convert markdown to HTML
    md = markdown.Markdown(extensions=["tables", "fenced_code"])
    content_html = md.convert(response)

    # Escape the question for HTML
    escaped_question = _escape_html(question[:80]) + (
        "..." if len(question) > 80 else ""
    )

    # Build full HTML with styling
    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6;
    color: #333333;
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f9f9f9;
}}
.header {{
    background: linear-gradient(135deg, #1a73e8, #0d47a1);
    color: white;
    padding: 24px;
    border-radius: 12px 12px 0 0;
}}
.header h1 {{
    margin: 0;
    font-size: 18px;
    color: white;
    font-weight: 600;
}}
.header .meta {{
    opacity: 0.9;
    font-size: 12px;
    margin-top: 8px;
    color: rgba(255,255,255,0.9);
}}
.content {{
    background: #ffffff;
    padding: 24px;
    border: 1px solid #e0e0e0;
    border-top: none;
    border-radius: 0 0 12px 12px;
}}
table {{
    border-collapse: collapse;
    width: 100%;
    margin: 16px 0;
    font-size: 14px;
    border: 1px solid #e0e0e0;
}}
th {{
    background-color: #f5f5f5;
    padding: 12px;
    text-align: left;
    border-bottom: 2px solid #1a73e8;
    font-weight: 600;
    color: #333333;
}}
td {{
    padding: 12px;
    border-bottom: 1px solid #eeeeee;
    color: #333333;
}}
tr {{
    background-color: #ffffff;
}}
h2 {{
    color: #1a73e8;
    border-bottom: 2px solid #1a73e8;
    padding-bottom: 8px;
    margin-top: 24px;
    margin-bottom: 16px;
    font-size: 20px;
}}
h3 {{
    color: #333333;
    margin-top: 20px;
    margin-bottom: 12px;
    font-size: 16px;
}}
p {{
    margin: 12px 0;
    color: #333333;
}}
strong {{
    color: #1a73e8;
    font-weight: 600;
}}
ul, ol {{
    margin: 12px 0;
    padding-left: 24px;
}}
li {{
    margin: 4px 0;
    color: #333333;
}}
code {{
    background-color: #f5f5f5;
    padding: 2px 6px;
    border-radius: 3px;
    font-family: monospace;
    font-size: 13px;
}}
pre {{
    background-color: #f5f5f5;
    padding: 12px;
    border-radius: 6px;
    overflow-x: auto;
    font-family: monospace;
    font-size: 13px;
}}
blockquote {{
    border-left: 4px solid #1a73e8;
    margin: 16px 0;
    padding-left: 16px;
    color: #666666;
    font-style: italic;
}}
hr {{
    border: none;
    border-top: 1px solid #e0e0e0;
    margin: 24px 0;
}}
.footer {{
    text-align: center;
    padding: 16px;
    color: #666666;
    font-size: 12px;
}}
.footer strong {{
    color: #1a73e8;
}}
</style>
</head>
<body>

<div class="header">
    <h1>🎿 {escaped_question}</h1>
    <div class="meta">Generated by Snowflake Intelligence | {datetime.now().strftime("%B %d, %Y at %I:%M %p")}</div>
</div>

<div class="content">
{content_html}
</div>

<div class="footer">
    <strong>Ski Resort Analytics</strong> | Powered by Snowflake Cortex<br/>
    <span style="font-size: 10px; color: #999999;">To manage alerts: "What alerts do I have?" or "Unsubscribe from [topic]"</span>
</div>

</body>
</html>"""

    # Inline CSS for email client compatibility
    try:
        premailer = Premailer(html, remove_classes=False)
        return premailer.transform()
    except Exception:
        # Fallback to raw HTML if premailer fails
        return html


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )
